
(defparameter *A1* '(role bill (supervisor self)))
(defparameter *A2* '(forall (A B) (implies (role A (supervisor B)) (is_superior A B))))
(defparameter *A3* '(forall X (iff (unsafe X) (permitted self (not X)))))
(defparameter *A4* '(forall (A B X) (implies (and (want B X) (is_superior B A))
                                           (obligated A X))))
(defparameter *A5* '(forall (A X) (implies (and (obligated A X) (not (permitted A (not X))))
                                         (goal A X))))
(defparameter *A6* '(want bill (did (walk self straight))))
(defparameter *A7* '(not (unsafe (did (walk self straight)))))
